### ISSUE TITLE
missing /

### ISSUE THREAD

**Issue by yachtsman60** [marcelo-ochoa/docker#1]
Hi Marcelo,
Thank you for your great work with Apex 5.1 and Oracle 12c.
I was trying to use your files but found that the Dockerfile is missing a / in line 8 which means the process fails to find the apex zip file.
Line 8 is currently RUN cd $INSTALL_DIR but should be RUN cd $INSTALL_DIR/ for the process to work.
Hope that helps.

**Comment by marcelo-ochoa** [comment]
Thanks for fix, Dockerfile updated. Marcelo.
